ALTER TABLE papers ADD COLUMN IF NOT EXISTS parse_mode VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE papers ADD COLUMN IF NOT EXISTS parse_error TEXT NOT NULL DEFAULT '';
ALTER TABLE papers ADD COLUMN IF NOT EXISTS parser_note TEXT NOT NULL DEFAULT '';

ALTER TABLE paper_insights ADD COLUMN IF NOT EXISTS extract_status VARCHAR(32) NOT NULL DEFAULT 'pending';
ALTER TABLE paper_insights ADD COLUMN IF NOT EXISTS extract_error TEXT NOT NULL DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS uk_paper_insights_paper_id ON paper_insights(paper_id);
